### ISSUE TITLE
Unifi mibs locations

### ISSUE THREAD

**Issue by rlex** [WaterByWind/grafana-dashboards#1]
Hello, hasn't found unifi mibs in update blog (probably buried too deep)
Here is official links AFAIK:
http://dl.ubnt-ut.com/snmp/UBNT-MIB
http://dl.ubnt-ut.com/snmp/UBNT-UniFi-MIB

**Comment by WaterByWind** [comment]
The _release announcements_ each have an item that references the MIB files.  There is no separate announcement just for these.

**Comment by rlex** [comment]
yup, but they all point to that two files. Just saying.
Thanks for dashboard btw, really useful.
