### ISSUE TITLE
Cannot find module IF-MIB

### ISSUE THREAD

**Issue by albundy83** [WaterByWind/grafana-dashboards#3]
Hello,

just a small error in log about a module not found:
```
Apr 13 16:28:00 my_server telegraf[25612]: 2017-04-13T14:28:00Z E! ERROR in input [inputs.snmp]: initializing table : translating: exit status 2: MIB search path: /etc/telegraf/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf:/usr/share/mibs/site:/usr/share/snmp/mibs:/usr/share/mibs/iana:/usr/share/mibs/ietf:/usr/share/mibs/netsnmp
Apr 13 16:28:00 my_server telegraf[25612]: Cannot find module (IF-MIB): At line 1 in (none)
Apr 13 16:28:00 my_server telegraf[25612]: IF-MIB::ifTable: Unknown Object Identifier
```
Maybe I forgot to install something ...

**Comment by WaterByWind** [comment]
If this is a debian or debian-derived system you may need to install `snmp-mibs-downloader` then run `sudo download-mibs`

If you do an `ls /usr/share/mibs` you should see two symlinks, one each for `iana` and `ietf`.  If not you may need to install the `snmp` package.

I'll update the notes to include an extra step `sudo apt install snmp-mibs-downloader snmp` just in case they are not already installed.

**Comment by albundy83** [comment]
Ah yes, thanks a lot !!
(and thanks for your great work :+1:  )
